services:
  db:
    image: chriswetherill/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro

  apollo:
    image: chriswetherill/apollo-server
    ports:
      - 4000:4000
    volumes:
      - ./apollo-server:/app:rw

  client:
    image: chriswetherill/react-client
    ports:
      - 3000:3000
    volumes:
      - ./client-app:/app:rw

